replicaCount: 1

mysql:
  databaseName: kubernetesdb

springApp:
  image:
    repository: spring-boot-mysql-k8s
    pullPolicy: IfNotPresent
    tag: latest

mysqlVolume:
  persistentVolumeClaim:
    storageSize: 1Gi #500Mi  #1Gi

  persistentVolume:
    storageSize: 1Gi #500Mi  #1Gi
    pathOnHost: /var/lib/mysql  # Replace this with the actual path on your host machine


  mountPath: /var/lib/mysql