apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    app: {{ .Release.Name }}-mysql # the selector should match the metadata labels app in the mysql-deployment
  ports:
      - protocol: TCP
        port: 3306
        targetPort: 3306
  type: ClusterIP